apply plugin: 'com.android.application'

android {
    compileSdkVersion rootProject.ext.android.compileSdkVersion   //Android10（API 29）getExternalStorageDirectory没权限，暂时使用28
    buildToolsVersion rootProject.ext.android.buildToolsVersion   //Android10（API 29）getExternalStorageDirectory没权限，暂时使用28

    defaultConfig {
        applicationId rootProject.ext.android.applicationId
        minSdkVersion rootProject.ext.android.minSdkVersion
        targetSdkVersion rootProject.ext.android.targetSdkVersion  //29   //Android10（API 29）getExternalStorageDirectory没权限，暂时使用28
        versionCode rootProject.ext.android.versionCode
        versionName rootProject.ext.android.versionName
//        multiDexEnabled rootProject.ext.android.multiDexEnabled  //开启之后在电视上起不来
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        platformCoocaa {
            storeFile file('../sign/platform_y41air.keystore')
            keyAlias 'skyworth'
            storePassword 'android'
            keyPassword 'android'
        }
        platformNormal {
            storeFile file('../sign/platform_y41.keystore')
            keyAlias 'skyworth'
            storePassword 'android'
            keyPassword 'android'
        }
        platformDunn{
            storeFile file('../sign/dunn.jks')
            keyAlias 'dunn'
            storePassword '123456'
            keyPassword '123456'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
//            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            shrinkResources false
            debuggable true
//            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            consumerProguardFiles 'proguard-rules.pro'
        }
    }

    android.applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "${variant.name}_${variant.versionName}_${variant.buildType.name}.apk"
        }
    }

    flavorDimensions "APP", "PLATFORM"
    productFlavors {
        "${project.name}" {
            dimension "APP"
            matchingFallbacks = ['Common']
        }
        y41air {
            dimension "PLATFORM"
            signingConfig signingConfigs.platformCoocaa
        }
        y41 {
            dimension "PLATFORM"
            signingConfig signingConfigs.platformNormal
        }
        dunn {
            dimension "PLATFORM"
            signingConfig signingConfigs.platformDunn
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar','*.aar'])
    compileOnly rootProject.ext.dependencies.appcompatV7
//    implementation 'com.github.zhuyidian:lib_Instrument_Tools:V1.1.0'
//    implementation project(":LibPromotion")
    implementation project(":LibFrameworks")
}
